### PR TITLE
Linux log fds more permissive

### LINKED ISSUE #429: Anonymous pipe permission too restrictive on linux
We have an application which drops privileges and expects
the /dev/stderr and /dev/stdout is openable after that.

We are using crio (crc 2.20).

Ruining example:

> root       24667  0.0  0.0   8308  2036 ?        Ss   07:49   0:00 /usr/bin/conmon -b /run/containers/storage/overlay-containers/4005b749174d7e3df64537db1cf10916c0722156a4b8020f088bc27e26d72d5e/userdata -c 4005b749174d7e3df64537db1cf10916c0722156a4b8020f088bc27e26d72d5e --exit-dir /var/run/crio/exits -l /var/log/pods/openstack_cinder-api-6f74cd6657-gqr6f_b00842f0-b252-4e50-94a2-ca09786c45ea/cinder-api/357.log --log-level info -n k8s_cinder-api_cinder-api-6f74cd6657-gqr6f_openstack_b00842f0-b252-4e50-94a2-ca09786c45ea_357 -P /run/containers/storage/overlay-containers/4005b749174d7e3df64537db1cf10916c0722156a4b8020f088bc27e26d72d5e/userdata/conmon-pidfile -p /run/containers/storage/overlay-containers/4005b749174d7e3df64537db1cf10916c0722156a4b8020f088bc27e26d72d5e/userdata/pidfile --persist-dir /var/lib/containers/storage/overlay-containers/4005b749174d7e3df64537db1cf10916c0722156a4b8020f088bc27e26d72d5e/userdata -r /usr/bin/runc --runtime-arg --root=/run/runc --socket-dir-path /var/run/crio --syslog -u 4005b749174d7e3df64537db1cf10916c0722156a4b8020f088bc27e26d72d5e -s

Minified not working app:

> #!/usr/bin/python
> 
> import os
> 
> uid = 1000
> 
> os.setuid(uid)
> os.seteuid(uid)
> f = open("/dev/stdout", "w")
> f.write("bar")
> f.close()

expected:

> $ oc logs test
> bar[zuul@host~]$

got:

>  oc logs test
> Traceback (most recent call last):
> File "/usr/bin/uidfork.py", line 9, in <module>
> f = open("/dev/stdout", "w")
> ^^^^^^^^^^^^^^^^^^^^^^^^
> PermissionError: [Errno 13] Permission denied: '/dev/stdout'

The open become working in 2020:
https://github.com/containers/conmon/pull/112

Not working around (2022):
https://github.com/containers/conmon/commit/32816bd66de4828daa178de0f20e8a6ea52b397f

Simple fix:

```
diff -Naur conmon-c26648e58b57312ccb513015bacdf40936d6400dorig/src/conmon.c conmon-c26648e58b57312ccb513015bacdf40936d6400d/src/conmon.c
--- conmon-c26648e58b57312ccb513015bacdf40936d6400dorig/src/conmon.c	2023-06-07 09:31:47.354796067 +0200
+++ conmon-c26648e58b57312ccb513015bacdf40936d6400d/src/conmon.c	2023-06-07 09:37:26.787842327 +0200
@@ -36,6 +36,13 @@
 
 #define DEFAULT_UMASK 0022
 
+#ifdef __linux__
+/* Linux does not needs tty check*/
+#define ISATTY(x) true
+#else
+#define ISATTY(x) isatty(x) 
+#endif
+
 int main(int argc, char *argv[])
 {
 	setlocale(LC_ALL, "");
@@ -240,21 +247,21 @@
 				workerfd_stdin = dev_null_r;
 			if (dup2(workerfd_stdin, STDIN_FILENO) < 0)
 				_pexit("Failed to dup over stdin");
-			if (workerfd_stdin != dev_null_r && isatty(workerfd_stdin) && fchmod(STDIN_FILENO, 0777) < 0)
+			if (workerfd_stdin != dev_null_r && ISATTY(workerfd_stdin) && fchmod(STDIN_FILENO, 0777) < 0)
 				nwarn("Failed to chmod stdin");
 
 			if (workerfd_stdout < 0)
 				workerfd_stdout = dev_null_w;
 			if (dup2(workerfd_stdout, STDOUT_FILENO) < 0)
 				_pexit("Failed to dup over stdout");
-			if (workerfd_stdout != dev_null_w && isatty(workerfd_stdout) && fchmod(STDOUT_FILENO, 0777) < 0)
+			if (workerfd_stdout != dev_null_w && ISATTY(workerfd_stdout) && fchmod(STDOUT_FILENO, 0777) < 0)
 				nwarn("Failed to chmod stdout");
 
 			if (workerfd_stderr < 0)
 				workerfd_stderr = workerfd_stdout;
 			if (dup2(workerfd_stderr, STDERR_FILENO) < 0)
 				_pexit("Failed to dup over stderr");
-			if (workerfd_stderr != dev_null_w && isatty(workerfd_stderr) && fchmod(STDERR_FILENO, 0777) < 0)
+			if (workerfd_stderr != dev_null_w && ISATTY(workerfd_stderr) && fchmod(STDERR_FILENO, 0777) < 0)
 				nwarn("Failed to chmod stderr");
 		}
 		/* If LISTEN_PID env is set, we need to set the LISTEN_PID
```

Should I send pull request or there is a better way to handle this ?

### PR DESCRIPTION
**Pull request by afazekas**
Since #112 the anonymous pipes are supposed to be
more permissive. Restoring the permissive state.

Close #429

### CODE REVIEW

File: src/conmon.c [hunk 1]
```diff
@@ -36,6 +36,13 @@ static void disconnect_std_streams(int dev_null_r, int dev_null_w)
 
 #define DEFAULT_UMASK 0022
 
+#ifdef __linux__
```
Comment (haircommander) [inline src/conmon.c:39]: typically, we check the inverse:
https://github.com/containers/conmon/pull/427/files
can we switch the case here?

**Comment by giuseppe** [comment]
why should this be done only on Linux?  I don't see it is arch specific.

I am afraid this will break passthrough mode as it changes the permissions of the files if used as std streams.

**Comment by afazekas** [comment]
The freebsd change introduced the tty check:
https://github.com/containers/conmon/commit/32816bd66de4828daa178de0f20e8a6ea52b397f

"I am afraid this will break passthrough mode as it changes the permissions of the files if used as std streams."
If I get you correctly, maybe the check should be something like `if not regular file` ?

**Comment by afazekas** [comment]
There is a check before:
https://github.com/containers/conmon/pull/430/commits/d6250d497ee514e169eef8863c75d894d2db1525#diff-737dc81597d3e3189077545b4907aae69cce646d12b5bc5938cfdd707882bd31R245
		if (!logging_is_passthrough()) {
		
Does it enough to save the passtrough mode ?

**Comment by giuseppe** [comment]
> There is a check before: [d6250d4#diff-737dc81597d3e3189077545b4907aae69cce646d12b5bc5938cfdd707882bd31R245](https://github.com/containers/conmon/commit/d6250d497ee514e169eef8863c75d894d2db1525#diff-737dc81597d3e3189077545b4907aae69cce646d12b5bc5938cfdd707882bd31R245) if (!logging_is_passthrough()) {
> 
> Does it enough to save the passtrough mode ?

thanks for checking that.  In this case, let's change the function name, since we are abusing `ISATTY`.  Could it be `should_use_chown(...)`?

**Comment by afazekas** [comment]
should_use_chmod as a lower case macro ?

**Comment by afazekas** [comment]
https://man.freebsd.org/cgi/man.cgi?query=chmod&sektion=2&apropos=0&manpath=solaris


       The fchmod() function may fail if:

       EINVAL	       The  fildes  argument  refers  to a pipe	and the	system
		       disallows execution of this function on a pipe.

**Comment by afazekas** [comment]
ignore and keeping the warning ? Or not even reporting it  on EINVAL ?

**Comment by afazekas** [comment]
I just finished a change.

Should I make the not reporting not platform specific ?

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@haircommander PTAL
